highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Alma Eguizabal's Resume
name: Alma Eguizabal
email: alma.eguizabal@ieee.org
email_full: mailto:alma.eguizabal@ieee.org
website: almaegui.github.io/
website_full: https://almaegui.github.io/
github: trending
twitter: twitter
tel: 
tel_full: 
google_maps: 'https://www.google.com/maps/place/KTH+Royal+Institute+of+Technology'
address:
  street:  Brinellvägen 8
  postcode: SE-100 44
  city: Stockholm
  country: Sweden
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
